name: Java CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Start Docker Service
      run: sudo service docker start  # Start Docker service
    - name: Build with Maven
      run: mvn -B package --file pom.xml -X
    - name: Run unit tests
      run: mvn test
    - name: Static code analysis
      continue-on-error: true
      run: mvn clean verify sonar:sonar -Pcoverage -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
    - name: Linting and formatting
      run: mvn spotless:apply
    - name: Conventional Commit check
      run: mvn validate -P validate-commit-message
    - name: Update README badge
      continue-on-error: true
      run: |
        # Update README badge with latest build status
        # (Assuming you have a script to generate badge)
        ./update_readme_badge.sh
    - name: Generate documentation
      run: mvn javadoc:javadoc
    - name: Deploy documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: target/site/apidocs
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }} 
    - name: Stop Docker Service
      run: sudo service docker stop  # Stop Docker service after completion
